name: CI/CD Pipeline Multiregion - Destroy

on: workflow_dispatch

env:
  AWS_ACCOUNT: "357834747308"

jobs:
  post-deployment-destroy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"

      - name: terraform init
        run: terraform init -backend-config=environment/backend.tfvars
        working-directory: ./post-deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"

      - name: terraform destroy
        run: terraform destroy --auto-approve -var-file=environment/terraform.tfvars
        working-directory: ./post-deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"

  sa-east-1-destroy:
    runs-on: ubuntu-latest
    needs:
      - post-deployment-destroy
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"

      - name: terraform init
        run: terraform init -backend-config=environment/sa-east-1/backend.tfvars
        working-directory: ./deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "sa-east-1"

      - name: terraform destroy
        run: terraform destroy --auto-approve -var-file=environment/sa-east-1/terraform.tfvars
        working-directory: ./deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "sa-east-1"

  us-east-1-destroy:
    runs-on: ubuntu-latest
    needs:
      - sa-east-1-destroy
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"

      - name: terraform init
        run: terraform init -backend-config=environment/us-east-1/backend.tfvars
        working-directory: ./deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"

      - name: terraform destroy
        run: terraform destroy --auto-approve -var-file=environment/us-east-1/terraform.tfvars
        working-directory: ./deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"

  pre-deployment-destroy:
    runs-on: ubuntu-latest
    needs:
      - us-east-1-destroy
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"

      - name: terraform init
        run: terraform init -backend-config=environment/backend.tfvars
        working-directory: ./pre-deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"

      - name: terraform destroy
        run: terraform destroy --auto-approve -var-file=environment/terraform.tfvars
        working-directory: ./pre-deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"